spring:
  config:
    import: "application-secrets.yml"
  datasource:
    url: jdbc:postgresql://localhost:5432/task_management_db
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create #для упрощения запуска приложения
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    jwt:
      secret: ${jwt.secret}
      expiration: ${jwt.expiration}
  logging:
    level:
      org.springframework.security: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs